CREATE INDEX "analysis_architecture_workspace_idx" ON "analysis_architecture" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_capability_workspace_idx" ON "analysis_capability" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_connected_repo_workspace_idx" ON "analysis_connected_repo" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_context_artifact_workspace_idx" ON "analysis_context_artifact" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_context_pipeline_idx" ON "analysis_context" USING btree ("pipeline_id");--> statement-breakpoint
CREATE INDEX "analysis_dependency_workspace_idx" ON "analysis_dependency" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_deployment_context_workspace_idx" ON "analysis_deployment_context" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_diagram_workspace_idx" ON "analysis_diagram" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_etiquette_workspace_idx" ON "analysis_etiquette" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_external_integration_workspace_idx" ON "analysis_external_integration" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_feature_workspace_idx" ON "analysis_feature" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_intra_dependency_workspace_idx" ON "analysis_intra_dependency" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_layer_workspace_idx" ON "analysis_layer" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_project_summary_workspace_idx" ON "analysis_project_summary" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_setup_workspace_idx" ON "analysis_setup" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "analysis_ux_workspace_idx" ON "analysis_ux" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "answer_created_by_user_idx" ON "answer" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "answer_version_created_by_user_idx" ON "answer_version" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "goal_version_created_by_user_idx" ON "goal_version" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "integration_audit_log_actor_user_idx" ON "integration_audit_log" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "linear_webhook_delivery_workspace_integration_idx" ON "linear_webhook_delivery" USING btree ("workspace_integration_id");--> statement-breakpoint
CREATE INDEX "pipeline_output_schema_idx" ON "pipeline" USING btree ("pipeline_output_schema_id");--> statement-breakpoint
CREATE INDEX "pull_request_trigger_installation_idx" ON "pull_request_trigger" USING btree ("installation_id");--> statement-breakpoint
CREATE INDEX "pull_request_trigger_workspace_idx" ON "pull_request_trigger" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_event_project_idx" ON "sandbox_lifecycle_event" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_event_repository_idx" ON "sandbox_lifecycle_event" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_event_goal_idx" ON "sandbox_lifecycle_event" USING btree ("goal_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_event_user_idx" ON "sandbox_lifecycle_event" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_snapshot_project_idx" ON "sandbox_lifecycle_snapshot" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_snapshot_repository_idx" ON "sandbox_lifecycle_snapshot" USING btree ("repository_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_snapshot_goal_idx" ON "sandbox_lifecycle_snapshot" USING btree ("goal_id");--> statement-breakpoint
CREATE INDEX "sandbox_lifecycle_snapshot_user_idx" ON "sandbox_lifecycle_snapshot" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "service_audit_log_service_key_idx" ON "service_audit_log" USING btree ("service_key_id");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "question_created_by_user_idx" ON "question" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "workflow_run_trigger_idx" ON "workflow_run" USING btree ("trigger_id");--> statement-breakpoint
CREATE INDEX "workflow_run_triggered_by_user_idx" ON "workflow_run" USING btree ("triggered_by_user_id");--> statement-breakpoint
CREATE INDEX "workspace_github_installation_connected_by_user_idx" ON "workspace_github_installation" USING btree ("connected_by_user_id");--> statement-breakpoint
CREATE INDEX "workspace_integration_connected_by_user_idx" ON "workspace_integration" USING btree ("connected_by_user_id");
